### ISSUE TITLE
Cannot preprocess ManyTypes4Py dataset

### ISSUE THREAD

**Issue by p-fruck** [saltudelft/type4py#15] opened 2023-06-04 00:45 UTC
Hey there,

I am currently trying to getting this project up and running and was following the instructions to train the model using the ManyTypes4Py dataset. Unfortunately, the preprocess command just skips the dataset (or rather, does not find any relevant information). I solved this issue by removing the files `all_fns.csv` and `all_vars.csv` and symlinking `processed_projects_complete` to `processed_projects`.

Did I miss anything during the setup? Are those steps expected and should be added to the documentation?

**Comment by mir-am** [comment] 2023-06-06 08:32
Hi @p-fruck,

Thanks for using Type4Py. Removing the mentioned files and renaming  `processed_projects_complete` to `processed_projects` solve the issue.
I need to push a hotfix for file name differences.

**Comment by mir-am** [comment] 2023-06-09 15:57
The issue is now fixed in [47b5397](https://github.com/saltudelft/type4py/commit/47b5397bcc2e1f6a16b3a6b3bb014b5e6bc1f0e7).

**Closed by mir-am** 2023-06-09 15:57 UTC
Labels: bug
